import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { registerLicense } from '@syncfusion/ej2-base';
registerLicense('Mgo+DSMBaFt/QHJqVVhjWlpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF9jTn9SdEdgXX9XdXNdQQ==;Mgo+DSMBPh8sVXJ0S0R+XE9HcFRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS3xTcURiW31ddHRcQ2lcVg==;ORg4AjUWIQA/Gnt2VVhiQlFadVlJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRdkJiWH1cc3BVT2ZcU0M=;Njc0MTA3QDMyMzAyZTMyMmUzMG1TZ1pDZ0NyTUI4NW15TE1wUXpsdG91QlFqZStNdlJFUjRHS3ZKVk00Y1E9;Njc0MTA4QDMyMzAyZTMyMmUzMG85TUxEcFlrZGdQTHdCcUp4MEYzSkJPSHptKy9VQktoN0p2TEl3azdobzQ9;NRAiBiAaIQQuGjN/V0Z+Xk9EaFxEVmJLYVB3WmpQdldgdVRMZVVbQX9PIiBoS35RdEVkWH5ccndRRmlUVEZz;Njc0MTEwQDMyMzAyZTMyMmUzMGdNK3EveUZBK0ZJTnNYc1N4c0tJQ0lUb1c0QjVRL3BNRUJXK3BEUFVwVms9;Njc0MTExQDMyMzAyZTMyMmUzMElNOFJ1dTMvR0hmT29ncTFjZUZMMFFubjk4akQraFJSU1VlWFpxaFdZc2c9;Mgo+DSMBMAY9C3t2VVhiQlFadVlJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRdkJiWH1cc3BVT2leUkE=;Njc0MTEzQDMyMzAyZTMyMmUzMGhaN04zODQ1NW0zTFlleUFtY2I1OUU1eEE3YVhKSnVtd00wRXltWXdXL3c9;Njc0MTE0QDMyMzAyZTMyMmUzMExtTU9oUkpseGFrbEsxR1NyYjlna3RkR1VmaTZRWG9FamxsNFdLeEwxK1k9;Njc0MTE1QDMyMzAyZTMyMmUzMGdNK3EveUZBK0ZJTnNYc1N4c0tJQ0lUb1c0QjVRL3BNRUJXK3BEUFVwVms9');
if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
